### ISSUE TITLE
Meetup #1

### ISSUE THREAD

**Issue by yaumianwar** [BugisDev/meetup#1]
#### Hasil Meet Up "What To Do Next

Materi:
- React (Ady Rahmat MA)
- Python (Dwi Sulfahnur)

Lokasi:
- CoWorking Space (eg. DiLo)  
- Coffe Shop [TIDAK KONDUSIF]

Waktu:
- 23 September 2017 / 30 September 2017
- Weekend

Target:
- 30 orang peserta

PJ :
Lokasi : Yaumi
Acara : Alif dan Dika
Design Flyer : Alif

#### Deadline
- 10 September 2017
   - Lokasi sudah harus fix
   - Materi sudah harus fix
   - Waktu pelaksanaan sudah harus fix
- 15 September 2017
   - Flyer sudah harus jadi
   - Publikasi Meet Up

**Comment by yaumianwar** [comment]
### Follow Up Persiapan Meet Up #1 BugisDev

- [x] Lokasi: STMIK Kharisma atau UIN Alauddin @ngurajeka 
- [x] Flyer (draft sudah ada) @dzalif 
- [x] Partner:
      - KelasX
      - KPM
- [ ] Code Of Conduct @Dikabaka 
- [ ] Create meetup di [meetup.com](https://www.meetup.com/BugisDev/)

**Comment by dikabaka** [comment]
Code Of Conduct 
1. Peserta wajib hadir 15 menit sebelum acara dimulai kecuali telah melakukan konfirmasi keterlambatan sebelumnya pada panitia.
2. Peserta wajib berpakaian rapi dan sopan.
3. Peserya wajib membawa laptop dan peralatan lain yang telah diwajibkan oleh panitia.
4. Jika hendak meninggalkan ruangan, peserta wajib melapor kepada panitia yang bersangkutan (Sie. Keamanan).
5. Peserta wajib menjaga ketertiban jalannya kegiatan 
6. Peserta wajib mengerjakan tugas yang diberikan pemateri maupun panitia.
7. Peserta wajib menggunakan tanda pengenal (ID Card) pada saat kegiatan berlangsung.
8. Peserta wajib membawa obat-obatan pribadi.
9. Peserta diwajibkan menjaga kebersihan lokasi kegiatan.
10. Pada saat kegiatan berlangsung, dilarang mengaktifkan nada dering handphone 
11. Peserta dilarang membawah senjata tajam dan dilarang merokok saat kegiatan.

**Comment by ngurajeka** [comment]
@Dikabaka commit sebagai file di repository biar historical pengeditannya
